export const REQUEST_HEROES = "REQUEST_HEROES";
export const RECEIVE_HEROES = "RECEIVE_HEROES";
export const SELECT_HERO = "SELECT_HERO";
export const SUGGEST_CHAMPIONS = "SUGGEST_CHAMPIONS";
export const RECEIVE_CHAMPIONS = "RECEIVE_CHAMPIONS";
