export const REQUEST_HEROES = "REQUEST_HEROES"
export const RECEIVE_HEROES = "RECEIVE_HEROES"
export const SELECT_HERO = "SELECT_HERO"
export const DESELECT_HERO = "DESELECT_HERO"
export const SUGGEST_CHAMPIONS = "SUGGEST_CHAMPIONS"
export const RECEIVE_SIMILARITIES = "RECEIVE_SIMILARITIES"
export const CLEAR_SELECTED_HEROES = "CLEAR_SELECTED_HEROES"
export const CLEAR_SUGGESTION_RESULTS = "CLEAR_SUGGESTION_RESULTS"

