export const REQUEST_HEROES = "REQUEST_HEROES";
export const RECEIVE_HEROES = "RECEIVE_HEROES";
export const SELECT_HERO = "SELECT_HERO";
export const REQUEST_CALCULATION = "CALCULATE_SIMILAR";
export const RECIEVE_CALCULATION = "RECEIVE_CALCULATION";
