default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: d2league_development
  username: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: d2league_test
  username: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: d2league_production
  username: d2league
  password: <%= ENV['D2LEAGUE_DATABASE_PASSWORD'] %>
